sonar.projectKey=devops-tp
sonar.projectName=devops-tp
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=node_modules/**,**/*.test.js
sonar.tests=.
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
