apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-tp-app
  namespace: devops-tp
  labels:
    app: devops-tp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-tp
  template:
    metadata:
      labels:
        app: devops-tp
    spec:
      automountServiceAccountToken: false
      containers:
      - name: devops-tp
        image: oussemaguerami/devops-tp:1.0.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
            ephemeral-storage: "128Mi"
          limits:
            memory: "128Mi"
            cpu: "200m"
            ephemeral-storage: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
