---
- name: Deploy devops-tp on Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    namespace: devops-tp
    docker_image: "oussemaguerami/devops-tp"
    docker_tag: "{{ lookup('env', 'DOCKER_TAG') }}"

  tasks:

    - name: Configure kubectl context to minikube
      shell: kubectl config use-context minikube
      changed_when: false

    - name: Deploy application with correct image
      shell: |
        sed 's|DOCKER_IMAGE_PLACEHOLDER|{{ docker_image }}:{{ docker_tag }}|g' \
        {{ playbook_dir }}/../k8s/deployment.yml | kubectl apply -f -

    - name: Apply Service
      shell: kubectl apply -f {{ playbook_dir }}/../k8s/service.yml

    - name: Apply Ingress
      shell: kubectl apply -f {{ playbook_dir }}/../k8s/ingress.yml

    - name: Wait for deployment to be ready
      shell: |
        kubectl rollout status deployment/devops-tp-app \
        -n {{ namespace }} --timeout=120s
      register: rollout_status

    - name: Show rollout status
      debug:
        msg: "{{ rollout_status.stdout }}"

    - name: Get pods status
      shell: kubectl get pods -n {{ namespace }}
      register: pods_status
      changed_when: false

    - name: Show pods
      debug:
        msg: "{{ pods_status.stdout }}"
